### ISSUE TITLE
发现有两个bug

### ISSUE THREAD

**Issue by gejun123456** [zhengjunbase/codehelper.generator#2]
1是不能在module 中genDao

2是当codehelperproperties存在时  生成的文件名 会出现 \ 符号 

这两个bug我在本地都已经修啦

代码在https://github.com/gejun123456/codehelper.generator/tree/develop  我的develop分支上

这是对比https://github.com/gejun123456/codehelper.generator/compare/master...gejun123456:develop?expand=1

可以给我一个push的权限吗  希望能在你这边开个branch来开发  这样也方便进行compare

**Comment by zhengjunbase** [comment]
好的，加我微信吧 zhengjun302
